version: '1'
services:
    jupyter:
        image: juppyr_container
        ports:
            - "8888:8888"
        volumes:
            - ./:/home/jovyan/work
        command: start-notebook.sh --NotebookApp.token=''